server:
  port: 8088
  tomcat:
    uri-encoding: utf-8
  servlet:
    context-path: /movieweb
logging:
  level:
    com.yonyou.mes: DEBUG
    tk.mybatis: DEBUG
    org.springframework: WARN
#  Controller: log/zb-shiro.log
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.19.86.199:3306/half_movie?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    # 初始化大小，最小，最大
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    filters: stat,wall,slf4j

  redis:
    host: 172.19.86.199
    port: 6379
    password:
    timeout: 5000
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    # 是否支持批量上传   (默认值 true)
  servlet:
    multipart:
      enabled: true
      # 上传文件的临时目录 （linux的默认临时目录定时会被删除会导致上传失败，尽量指定临时目录）
      location:
      # 上传文件最大为 1M （默认值 1M 根据自身业务自行控制即可）
      max-file-size: 1MB
      # 设置总上传的数据大小 10M（默认值10M 根据自身业务自行控制即可）
      max-request-size: 1MB
      # 文件大小阈值，当大于这个阈值时将写入到磁盘，否则存在内存中，（默认值0 一般情况下不用特意修改）
      file-size-threshold: 0
mybatis-plus:
  type-aliases-package: com.half.movie
  mapper-locations: classpath*:com/half/movie/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
  global-config:
    db-config:

      #逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0
      #主键类型 0:数据库自增 1.用户输入ID 2.全局唯一ID(数字类型ID) 3.全局唯一ID UUID
      id-type: assign_uuid
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
config:
  # AccessToken过期时间(秒)
  jwtToken-expireTime: 7200
  # RefreshToken过期时间(秒)
  redisToken-expireTime: 60
  # shiro权限缓存过期时间(秒)
  shiro-cache-expireTime: 86400
  # springboot2.2.x 默认不支持delete put等请求方式
  # 必须在此处配置开启
  mvc:
    hiddenmethod:
      filter:
        enabled: true

#  微信小程序配置 appid /appsecret
wx:
  applet:
    appid: wx75ee1fe62e2045ed
    appsecret: f5dc6531807bc226e7f0e0c0fd4736b6
